# Generated by Django 5.1.2 on 2024-11-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('editora', models.CharField(max_length=255, verbose_name='Editora')),
                ('ano_publicacao', models.PositiveIntegerField(verbose_name='Ano de Publicação')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('quantidade_disponivel', models.PositiveIntegerField(verbose_name='Quantidade Disponível')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('em_aberto', 'Em Aberto'), ('concluido', 'Concluído')], default='em_aberto', max_length=20, verbose_name='Status')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('fk_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.livro', verbose_name='Livro')),
            ],
        ),
        migrations.CreateModel(
            name='Contem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_emprestada', models.PositiveIntegerField(verbose_name='Quantidade emprestada')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.emprestimo', verbose_name='Empréstimo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.livro', verbose_name='Livro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=22, verbose_name='Telefone')),
                ('usuairo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
