# Generated by Django 5.1.2 on 2024-11-04 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_emprestimo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(default=datetime.date(2024, 11, 11), verbose_name='Data de Devolução'),
        ),
    ]
