# Generated by Django 5.1.2 on 2024-11-05 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 18, 24, 4, 69667, tzinfo=datetime.timezone.utc), verbose_name='Data do Empréstimo'),
        ),
    ]
